"""Varex Imaging (VREX) DCF + trading comps valuation.

This project is built for interview use and shows a clean, explainable valuation
process. It is intentionally transparent: the financial logic is written in code,
comments and docstrings, and each key concept is exposed rather than hidden in a
black box.

Key concepts explained in this model:
- WACC: blended required return for debt and equity holders.
- UFCF: cash generated by the business before financing effects.
- Terminal value: value assigned to cash flows beyond the explicit forecast.
- Sensitivity analysis: how intrinsic value changes as WACC and terminal growth
  move.
- Trading comps: equity market valuation based on peer multiples.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yfinance as yf

OFFER_PRICE = 18.90
TICKER = "VREX"
COMPS = ["GEHC", "TDY"]
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)


def normalize_financial_frame(frame: pd.DataFrame) -> pd.DataFrame:
    """yfinance returns statements with dates as columns; convert to rows for ease.

    This makes it easier to build and compare annual metrics over time.
    """
    if frame is None or frame.empty:
        return pd.DataFrame()
    df = frame.T.copy()
    df.index = pd.to_datetime(df.index)
    df = df.sort_index()
    return df


def pick_metric(frame: pd.DataFrame, candidates: Iterable[str]) -> str:
    """Return the closest matching column name for a metric.

    yfinance column names are not perfectly consistent across statements, so we
    look for a close match rather than hard-coding one exact string.
    """
    if frame.empty:
        return ""

    normalized = {str(col).lower(): col for col in frame.columns}
    candidate_tokens = set()
    for candidate in candidates:
        candidate_key = str(candidate).lower().replace("&", " ").replace("/", " ")
        candidate_tokens.update(candidate_key.replace("-", " ").split())
        if candidate_key in normalized:
            return normalized[candidate_key]

    for candidate in candidates:
        candidate_key = str(candidate).lower().replace("&", " ").replace("/", " ")
        for col_name, actual_name in normalized.items():
            col_lower = str(col_name).lower()
            if candidate_key in col_lower or col_lower in candidate_key:
                return actual_name

    for actual_name in normalized.values():
        actual_lower = str(actual_name).lower()
        if any(token in actual_lower for token in candidate_tokens if len(token) >= 3):
            return actual_name

    return ""


def fetch_statement_data(symbol: str) -> Dict[str, pd.DataFrame]:
    """Download the last five years of financial statements for a stock."""
    ticker = yf.Ticker(symbol)
    data = {
        "income": normalize_financial_frame(ticker.financials),
        "balance": normalize_financial_frame(ticker.balance_sheet),
        "cashflow": normalize_financial_frame(ticker.cashflow),
        "history": ticker.history(period="5y", interval="1d"),
        "info": ticker.info,
        "ticker": ticker,
    }
    return data


def latest_value(series: pd.Series) -> float:
    """Return the latest non-null value in a series."""
    valid = series.dropna()
    return float(valid.iloc[-1]) if not valid.empty else np.nan


def robust_tax_rate(income: pd.DataFrame) -> float:
    """Return a sensible tax rate even when the company had temporary losses.

    DCF models cannot treat a one-year loss as a valid negative tax rate. We use a
    non-negative, bounded, realized tax burden from recent history so the model is
    stable and explainable.
    """
    tax_key = pick_metric(income, ["Income Tax Expense", "Tax Expense", "Tax Provision", "Taxes", "Income Tax Provision"])
    pretax_key = pick_metric(income, ["Income Before Tax", "Pretax Income", "Earnings Before Tax", "Taxable Income"])
    if not tax_key or not pretax_key:
        return 0.25

    tax_series = income[tax_key].replace(0, np.nan).abs()
    pretax_series = income[pretax_key].replace(0, np.nan).abs()
    ratios = tax_series / pretax_series
    valid = ratios.replace([np.inf, -np.inf], np.nan).dropna()
    if valid.empty:
        return 0.25
    return float(np.clip(valid.median(), 0.0, 0.35))


def build_history_metrics(income: pd.DataFrame, balance: pd.DataFrame, cashflow: pd.DataFrame) -> pd.DataFrame:
    """Construct the historical series used to estimate the forecast.

    We build a compact table with the metrics that matter most for a DCF:
    - revenue
    - EBITDA-ish operating profit
    - effective tax rate
    - capex
    - D&A
    - net working capital proxy
    """
    revenue_key = pick_metric(income, ["Total Revenue", "Revenue", "Operating Revenue", "Net Sales"])
    ebit_key = pick_metric(income, ["Operating Income", "EBIT", "Income Before Tax", "Pretax Income"])
    tax_key = pick_metric(income, ["Income Tax Expense", "Tax Expense", "Tax Provision", "Taxes", "Income Tax Provision"])
    pretax_key = pick_metric(income, ["Income Before Tax", "Pretax Income", "Earnings Before Tax", "Operating Income Before Tax"])

    dep_key = pick_metric(cashflow, ["Depreciation", "Depreciation And Amortization", "D&A", "Amortization", "Reconciled Depreciation"])
    capex_key = pick_metric(cashflow, ["Capital Expenditures", "Capital Expenditure", "Purchase Of Property Plant And Equipment", "Capital expenditure"])

    current_assets_key = pick_metric(balance, ["Total Current Assets", "Current Assets", "Assets Current"])
    current_liab_key = pick_metric(balance, ["Total Current Liabilities", "Current Liabilities", "Liabilities Current"])
    cash_key = pick_metric(balance, ["Cash And Cash Equivalents", "Cash", "Cash And Short Term Investments"])
    debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt", "Net Debt"])

    hist = pd.DataFrame(index=income.index)
    hist["Revenue"] = income[revenue_key] if revenue_key else pd.Series(np.nan, index=income.index)
    hist["EBIT"] = income[ebit_key] if ebit_key else pd.Series(np.nan, index=income.index)
    hist["Tax Expense"] = income[tax_key] if tax_key else pd.Series(np.nan, index=income.index)
    hist["Pretax Income"] = income[pretax_key] if pretax_key else pd.Series(np.nan, index=income.index)
    hist["Depreciation"] = cashflow[dep_key] if dep_key else pd.Series(np.nan, index=income.index)
    hist["Capex"] = (-cashflow[capex_key]) if capex_key else pd.Series(np.nan, index=income.index)

    if current_assets_key and current_liab_key:
        hist["NWC"] = balance[current_assets_key] - balance[current_liab_key]
        if cash_key:
            hist["NWC"] = hist["NWC"] - balance[cash_key]
        if debt_key:
            hist["NWC"] = hist["NWC"] + balance[debt_key]
    else:
        hist["NWC"] = np.nan

    tax_series = hist["Tax Expense"].copy() if "Tax Expense" in hist.columns else hist["Tax Provision"].copy() if "Tax Provision" in hist.columns else pd.Series(np.nan, index=hist.index)
    pretax_series = hist["Pretax Income"].copy() if "Pretax Income" in hist.columns else hist["Income Before Tax"].copy() if "Income Before Tax" in hist.columns else pd.Series(np.nan, index=hist.index)

    hist["Tax Rate"] = tax_series / pretax_series.replace(0, np.nan)
    hist["EBIT Margin"] = hist["EBIT"] / hist["Revenue"]
    hist["Capex Margin"] = hist["Capex"] / hist["Revenue"]
    hist["D&A Margin"] = hist["Depreciation"] / hist["Revenue"]
    hist["NWC Margin"] = hist["NWC"] / hist["Revenue"]

    return hist.dropna(how="all")


def build_ufcf_projection(hist: pd.DataFrame, years: int = 5) -> pd.DataFrame:
    """Project unlevered free cash flow for five years.

    The logic is:
    EBIT x (1 - tax rate) = NOPAT
    + depreciation = non-cash expense added back
    - capex = cash reinvestment needed to maintain the asset base
    - change in net working capital = cash tied up in the business
    = UFCF
    """
    latest_year = hist.iloc[-1]
    revenue_growth = (latest_year["Revenue"] / hist["Revenue"].iloc[0]) ** (1 / max(len(hist) - 1, 1)) - 1
    revenue_growth = float(np.clip(revenue_growth, -0.10, 0.12))

    ebit_margin = hist["EBIT Margin"].dropna().mean()
    tax_rate = hist["Tax Rate"].dropna().median()
    d_and_a_margin = hist["D&A Margin"].dropna().mean()
    capex_margin = hist["Capex Margin"].dropna().mean()
    nwc_margin = hist["NWC Margin"].dropna().mean()

    revenue_forecast = []
    base_revenue = float(latest_year["Revenue"])
    for year in range(1, years + 1):
        revenue_forecast.append(base_revenue * (1 + revenue_growth) ** year)

    forecast = pd.DataFrame({
        "Year": np.arange(1, years + 1),
        "Revenue": revenue_forecast,
    })
    forecast["EBIT"] = forecast["Revenue"] * ebit_margin
    forecast["Tax Rate"] = tax_rate
    forecast["NOPAT"] = forecast["EBIT"] * (1 - forecast["Tax Rate"])
    forecast["D&A"] = forecast["Revenue"] * d_and_a_margin
    forecast["Capex"] = forecast["Revenue"] * capex_margin
    forecast["NWC"] = forecast["Revenue"] * nwc_margin

    # We calculate the change in NWC year-over-year. This captures the cash the
    # business needs to keep tied up in operations.
    forecast["Delta NWC"] = forecast["NWC"].diff().fillna(0.0)
    forecast["UFCF"] = (
        forecast["NOPAT"]
        + forecast["D&A"]
        - forecast["Capex"]
        - forecast["Delta NWC"]
    )

    return forecast


def estimate_cost_of_debt(balance: pd.DataFrame, income: pd.DataFrame) -> float:
    """Estimate the after-tax cost of debt from actual interest burden.

    Cost of debt is approximated as interest expense divided by average debt, then
    adjusted by the tax shield. This is a workable debt proxy when market debt
    yields are not available.
    """
    interest_key = pick_metric(income, ["Interest Expense", "Interest And Debt Expense", "Interest Expense Net"])
    debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])

    if not interest_key or not debt_key:
        return 0.052

    latest_interest = latest_value(income[interest_key])
    latest_debt = latest_value(balance[debt_key])
    if np.isnan(latest_interest) or np.isnan(latest_debt) or latest_debt <= 0:
        return 0.052

    tax_rate = robust_tax_rate(income)
    pre_tax_cost_debt = latest_interest / latest_debt if latest_debt > 0 else 0.06
    return float(pre_tax_cost_debt * (1 - tax_rate))


def estimate_capm_wacc(info: Dict, balance: pd.DataFrame, income: pd.DataFrame) -> Dict[str, float]:
    """Estimate WACC using CAPM for cost of equity and book debt weights.

    WACC is the blended required return for all capital providers:
    WACC = E/V * Re + D/V * Rd * (1 - tax rate)
    """
    market_cap = float(info.get("marketCap", 0.0) or 0.0)
    shares = float(info.get("sharesOutstanding", 0.0) or 0.0)
    price = float(info.get("currentPrice", 0.0) or 0.0)
    if market_cap <= 0 and price > 0 and shares > 0:
        market_cap = price * shares

    debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])
    debt = latest_value(balance[debt_key]) if debt_key else 0.0

    if debt <= 0:
        debt = 0.0

    beta = float(info.get("beta", 1.2) or 1.2)
    risk_free = 0.042  # Approximate 10-year US Treasury yield.
    market_risk_premium = 0.05
    cost_of_equity = risk_free + beta * market_risk_premium

    cost_of_debt = estimate_cost_of_debt(balance, income)
    tax_rate = robust_tax_rate(income)
    tax_rate = float(np.clip(tax_rate, 0.0, 0.35))

    total_capital = market_cap + debt
    if total_capital <= 0:
        weight_equity = 0.7
        weight_debt = 0.3
    else:
        weight_equity = market_cap / total_capital
        weight_debt = debt / total_capital

    wacc = weight_equity * cost_of_equity + weight_debt * cost_of_debt * (1 - tax_rate)

    return {
        "beta": beta,
        "risk_free": risk_free,
        "market_risk_premium": market_risk_premium,
        "cost_of_equity": cost_of_equity,
        "cost_of_debt": cost_of_debt,
        "after_tax_cost_of_debt": cost_of_debt * (1 - tax_rate),
        "wacc": wacc,
        "weight_equity": weight_equity,
        "weight_debt": weight_debt,
    }


def discount_cash_flows(ufcf: pd.DataFrame, wacc: float) -> pd.DataFrame:
    """Discount explicit forecast cash flows back to present value.

    Each projected year is discounted by (1 + WACC)^t. This converts future
    value into today's dollars using the firm's required return.
    """
    df = ufcf.copy()
    df["PV Factor"] = (1 + wacc) ** df["Year"]
    df["PV UFCF"] = df["UFCF"] / df["PV Factor"]
    return df


def terminal_value_gordon(ufcf: pd.DataFrame, wacc: float, terminal_growth: float) -> float:
    """Gordon growth model terminal value.

    The terminal value assumes the firm grows at a steady rate forever after the
    explicit forecast ends. In practice, this should be below long-run nominal GDP
    growth and below the company's sustainable growth rate.
    """
    if wacc <= terminal_growth:
        return np.nan
    year_6_fcf = float(ufcf["UFCF"].iloc[-1] * (1 + terminal_growth))
    tv = year_6_fcf / (wacc - terminal_growth)
    return tv


def build_exit_multiple_comps(comp_symbols: List[str]) -> pd.DataFrame:
    """Cross-check the Gordon growth TV with an EV/EBITDA exit multiple.

    The idea is simple: an acquirer may pay a market multiple on the business's
    earnings power at the point of sale. We compare Varex against relevant peers
    to see whether the DCF terminal value is realistic.
    """
    rows = []
    for symbol in comp_symbols:
        data = fetch_statement_data(symbol)
        info = data["info"]
        income = data["income"]
        balance = data["balance"]
        cashflow = data["cashflow"]

        market_cap = float(info.get("marketCap", 0.0) or 0.0)
        if market_cap <= 0:
            shares = float(info.get("sharesOutstanding", 0.0) or 0.0)
            price = float(info.get("currentPrice", 0.0) or 0.0)
            market_cap = shares * price

        debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])
        cash_key = pick_metric(balance, ["Cash And Cash Equivalents", "Cash", "Cash And Short Term Investments"])
        debt = latest_value(balance[debt_key]) if debt_key else 0.0
        cash = latest_value(balance[cash_key]) if cash_key else 0.0

        ebitda_key = pick_metric(income, ["EBITDA", "Operating Income", "Earnings Before Interest Taxes Depreciation And Amortization"])
        if not ebitda_key:
            dep_key = pick_metric(cashflow, ["Depreciation", "Depreciation And Amortization", "D&A", "Amortization"])
            op_key = pick_metric(income, ["Operating Income", "EBIT", "Income Before Tax"])
            ebitda = latest_value(income[op_key]) + latest_value(cashflow[dep_key])
        else:
            ebitda = latest_value(income[ebitda_key])

        if np.isnan(ebitda) or ebitda <= 0:
            ebitda = 1.0

        ev = market_cap + debt - cash
        ev_ebitda = ev / ebitda
        rows.append({
            "Ticker": symbol,
            "MarketCap": market_cap,
            "Debt": debt,
            "Cash": cash,
            "EV": ev,
            "EBITDA": ebitda,
            "EV_EBITDA": ev_ebitda,
        })

    return pd.DataFrame(rows)


def estimate_value_per_share_via_dcf(symbol: str, offer_price: float = OFFER_PRICE) -> Dict[str, float]:
    """Run the full DCF and return valuation metrics.

    This yields a price estimate per share, which can then be compared directly
    with the acquisition offer in the deal note.
    """
    data = fetch_statement_data(symbol)
    income = data["income"]
    balance = data["balance"]
    cashflow = data["cashflow"]
    info = data["info"]
    hist = build_history_metrics(income, balance, cashflow)
    forecast = build_ufcf_projection(hist, years=5)

    wacc_info = estimate_capm_wacc(info, balance, income)
    wacc = float(wacc_info["wacc"])
    terminal_growth = 0.025

    pv = discount_cash_flows(forecast, wacc)
    pv_terminal = terminal_value_gordon(forecast, wacc, terminal_growth) / ((1 + wacc) ** 5)
    enterprise_value = float(pv["PV UFCF"].sum() + pv_terminal)

    debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])
    cash_key = pick_metric(balance, ["Cash And Cash Equivalents", "Cash", "Cash And Short Term Investments"])
    debt = latest_value(balance[debt_key]) if debt_key else 0.0
    cash = latest_value(balance[cash_key]) if cash_key else 0.0
    net_debt = debt - cash

    shares = float(info.get("sharesOutstanding", 0.0) or 0.0)
    last_price = float(info.get("currentPrice", 0.0) or 0.0)
    if shares <= 0 and last_price > 0:
        shares = float(info.get("marketCap", 0.0) or 0.0) / last_price

    equity_value = enterprise_value - net_debt
    implied_price = equity_value / shares if shares > 0 else np.nan

    comps = build_exit_multiple_comps(COMPS)
    exit_multiple = float(comps["EV_EBITDA"].median())
    terminal_ebitda = float(forecast["EBIT"].iloc[-1] + forecast["D&A"].iloc[-1])
    tv_exit = terminal_ebitda * exit_multiple
    pv_exit = tv_exit / ((1 + wacc) ** 5)
    enterprise_value_exit = float(pv["PV UFCF"].sum() + pv_exit)
    implied_price_exit = (enterprise_value_exit - net_debt) / shares if shares > 0 else np.nan

    summary = {
        "wacc": wacc,
        "terminal_growth": terminal_growth,
        "beta": wacc_info["beta"],
        "cost_of_equity": wacc_info["cost_of_equity"],
        "after_tax_cost_of_debt": wacc_info["after_tax_cost_of_debt"],
        "weight_equity": wacc_info["weight_equity"],
        "weight_debt": wacc_info["weight_debt"],
        "enterprise_value_dcf": enterprise_value,
        "enterprise_value_exit_multiple": enterprise_value_exit,
        "implied_share_price_dcf": implied_price,
        "implied_share_price_exit_multiple": implied_price_exit,
        "offer_price": offer_price,
        "upside_vs_offer": implied_price / offer_price - 1,
        "gordon_terminal_value": terminal_value_gordon(forecast, wacc, terminal_growth),
        "exit_multiple": exit_multiple,
        "forecast_table": forecast,
        "discounted_table": pv,
        "comps_table": comps,
    }
    return summary


def make_sensitivity_heatmap(summary: Dict[str, float]) -> None:
    """Create a 2D sensitivity table for WACC vs terminal growth.

    This is a classic DCF sensitivity analysis: for different required returns and
    long-run growth rates, the implied share price changes materially. The chart
    shows the range around the offer price clearly.
    """
    data = fetch_statement_data(TICKER)
    hist = build_history_metrics(data["income"], data["balance"], data["cashflow"])
    forecast = build_ufcf_projection(hist, years=5)

    wacc_grid = np.linspace(0.04, 0.12, 9)
    growth_grid = np.linspace(0.01, 0.05, 9)
    values = np.zeros((len(wacc_grid), len(growth_grid)))

    debt_key = pick_metric(data["balance"], ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])
    cash_key = pick_metric(data["balance"], ["Cash And Cash Equivalents", "Cash", "Cash And Short Term Investments"])
    debt = latest_value(data["balance"][debt_key]) if debt_key else 0.0
    cash = latest_value(data["balance"][cash_key]) if cash_key else 0.0
    net_debt = debt - cash
    shares = float(data["info"].get("sharesOutstanding", 0.0) or 0.0)
    if shares <= 0:
        shares = (float(data["info"].get("marketCap", 0.0) or 0.0) / max(float(data["info"].get("currentPrice", 0.0) or 0.0), 1.0))

    for i, wacc in enumerate(wacc_grid):
        pv = discount_cash_flows(forecast, wacc)
        for j, g in enumerate(growth_grid):
            tv = terminal_value_gordon(forecast, wacc, g)
            if np.isnan(tv):
                values[i, j] = np.nan
                continue
            ev = pv["PV UFCF"].sum() + tv / ((1 + wacc) ** 5)
            values[i, j] = (ev - net_debt) / shares

    plt.figure(figsize=(9, 7))
    ax = plt.gca()
    heatmap = ax.imshow(values, cmap="RdYlGn_r", aspect="auto", origin="lower")
    ax.set_xticks(range(len(growth_grid)))
    ax.set_yticks(range(len(wacc_grid)))
    ax.set_xticklabels([f"{g:.2%}" for g in growth_grid])
    ax.set_yticklabels([f"{w:.2%}" for w in wacc_grid])
    ax.set_xlabel("Terminal growth rate")
    ax.set_ylabel("WACC")
    ax.set_title("VREX implied share value sensitivity: WACC x terminal growth")

    for i in range(len(wacc_grid)):
        for j in range(len(growth_grid)):
            ax.text(j, i, f"${values[i, j]:.1f}", ha="center", va="center", color="black", fontsize=8)

    for idx, value in enumerate(values.flatten()):
        if abs(value - OFFER_PRICE) < 0.5:
            i = idx // len(growth_grid)
            j = idx % len(growth_grid)
            ax.scatter(j, i, s=80, facecolors="none", edgecolors="black", linewidths=1.5)

    plt.colorbar(heatmap, ax=ax, label="Implied share value ($)")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "wacc_growth_sensitivity.png", dpi=200)
    plt.close()


def make_implied_value_chart(summary: Dict[str, float]) -> None:
    """Create a simple value-vs-offer chart for presentation.

    This is not meant to be the only metric, but it is a clear way to frame the
    investment decision in a discussion or interview.
    """
    labels = ["DCF intrinsic value", "Exit multiple value", "Offer price"]
    values = [
        summary["implied_share_price_dcf"],
        summary["implied_share_price_exit_multiple"],
        OFFER_PRICE,
    ]

    plt.figure(figsize=(7, 5))
    bars = plt.bar(labels, values, color=["#2a7ae2", "#6ab36d", "#d65f5f"])
    plt.axhline(OFFER_PRICE, color="black", linestyle="--", linewidth=1.0, label="Offer price")
    plt.ylabel("Share value ($)")
    plt.title("VREX implied value vs. Teledyne offer")
    plt.grid(axis="y", linestyle="--", alpha=0.3)
    for bar, value in zip(bars, values):
        plt.text(bar.get_x() + bar.get_width() / 2, value + 0.4, f"${value:.2f}", ha="center", va="bottom")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "implied_value_vs_offer.png", dpi=200)
    plt.close()


def main() -> None:
    """Run the full valuation workflow and save clean outputs."""
    summary = estimate_value_per_share_via_dcf(TICKER, OFFER_PRICE)

    # Save the DCF summary in CSV format so the key outputs are easy to inspect or
    # present in an interview slide.
    summary_table = pd.DataFrame([
        {
            "Metric": "WACC",
            "Value": summary["wacc"],
        },
        {
            "Metric": "Beta",
            "Value": summary["beta"],
        },
        {
            "Metric": "Cost of equity",
            "Value": summary["cost_of_equity"],
        },
        {
            "Metric": "After-tax cost of debt",
            "Value": summary["after_tax_cost_of_debt"],
        },
        {
            "Metric": "Enterprise value (DCF)",
            "Value": summary["enterprise_value_dcf"],
        },
        {
            "Metric": "Gordon terminal value",
            "Value": summary["gordon_terminal_value"],
        },
        {
            "Metric": "Implied share price (DCF)",
            "Value": summary["implied_share_price_dcf"],
        },
        {
            "Metric": "Implied share price (exit multiple)",
            "Value": summary["implied_share_price_exit_multiple"],
        },
        {
            "Metric": "Offer price",
            "Value": summary["offer_price"],
        },
        {
            "Metric": "Upside vs offer",
            "Value": summary["upside_vs_offer"],
        },
    ])
    summary_table.to_csv(OUTPUT_DIR / "vrex_dcf_summary.csv", index=False)

    make_sensitivity_heatmap(summary)
    make_implied_value_chart(summary)

    print("WACC:", round(summary["wacc"], 4))
    print("Beta:", round(summary["beta"], 3))
    print("Implied share price (DCF): $", round(summary["implied_share_price_dcf"], 2))
    print("Implied share price (exit multiple): $", round(summary["implied_share_price_exit_multiple"], 2))
    print("Offer price: $", round(summary["offer_price"], 2))
    print("Upside vs offer:", round(summary["upside_vs_offer"] * 100, 2), "%")
    print("Comparable EV/EBITDA median:", round(summary["exit_multiple"], 2), "x")

    print("\nNotes:")
    print("- Varex does not have a clean pure-play public comp; GEHC and TDY are used only as directional cross-checks.")
    print("- The sensitivity heatmap and value charts were saved in the output folder.")


if __name__ == "__main__":
    main()
