"""Varex Imaging (VREX) DCF + trading comps valuation.

This project is built for interview use and shows a clean, explainable valuation
process. It is intentionally transparent: the financial logic is written in code,
comments and docstrings, and each key concept is exposed rather than hidden in a
black box.

Key concepts explained in this model:
- WACC: blended required return for debt and equity holders.
- UFCF: cash generated by the business before financing effects.
- Terminal value: value assigned to cash flows beyond the explicit forecast.
- Sensitivity analysis: how intrinsic value changes as WACC and terminal growth
  move.
- Trading comps: equity market valuation based on peer multiples.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yfinance as yf

OFFER_PRICE = 18.90
TICKER = "VREX"
COMPS = ["GEHC", "TDY"]
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)


def normalize_financial_frame(frame: pd.DataFrame) -> pd.DataFrame:
    """yfinance returns statements with dates as columns; convert to rows for ease.

    This makes it easier to build and compare annual metrics over time.
    """
    if frame is None or frame.empty:
        return pd.DataFrame()
    df = frame.T.copy()
    df.index = pd.to_datetime(df.index)
    df = df.sort_index()
    return df


def pick_metric(frame: pd.DataFrame, candidates: Iterable[str]) -> str:
    """Return the closest matching column name for a metric.

    yfinance column names are not perfectly consistent across statements, so we
    look for a close match rather than hard-coding one exact string.
    """
    if frame.empty:
        return ""

    normalized = {str(col).lower(): col for col in frame.columns}
    candidate_tokens = set()
    for candidate in candidates:
        candidate_key = str(candidate).lower().replace("&", " ").replace("/", " ")
        candidate_tokens.update(candidate_key.replace("-", " ").split())
        if candidate_key in normalized:
            return normalized[candidate_key]

    for candidate in candidates:
        candidate_key = str(candidate).lower().replace("&", " ").replace("/", " ")
        for col_name, actual_name in normalized.items():
            col_lower = str(col_name).lower()
            if candidate_key in col_lower or col_lower in candidate_key:
                return actual_name

    for actual_name in normalized.values():
        actual_lower = str(actual_name).lower()
        if any(token in actual_lower for token in candidate_tokens if len(token) >= 3):
            return actual_name

    return ""


def fetch_statement_data(symbol: str) -> Dict[str, pd.DataFrame]:
    """Download the last five years of financial statements for a stock."""
    ticker = yf.Ticker(symbol)
    data = {
        "income": normalize_financial_frame(ticker.financials),
        "balance": normalize_financial_frame(ticker.balance_sheet),
        "cashflow": normalize_financial_frame(ticker.cashflow),
        "history": ticker.history(period="5y", interval="1d"),
        "info": ticker.info,
        "ticker": ticker,
    }
    return data


def latest_value(series: pd.Series) -> float:
    """Return the latest non-null value in a series."""
    valid = series.dropna()
    return float(valid.iloc[-1]) if not valid.empty else np.nan


def robust_tax_rate(income: pd.DataFrame) -> float:
    """Return a sensible tax rate even when the company had temporary losses.

    DCF models cannot treat a one-year loss as a valid negative tax rate. We use a
    non-negative, bounded, realized tax burden from recent history so the model is
    stable and explainable.
    """
    tax_key = pick_metric(income, ["Income Tax Expense", "Tax Expense", "Tax Provision", "Taxes", "Income Tax Provision"])
    pretax_key = pick_metric(income, ["Income Before Tax", "Pretax Income", "Earnings Before Tax", "Taxable Income"])
    if not tax_key or not pretax_key:
        return 0.25

    tax_series = income[tax_key].replace(0, np.nan).abs()
    pretax_series = income[pretax_key].replace(0, np.nan).abs()
    ratios = tax_series / pretax_series
    valid = ratios.replace([np.inf, -np.inf], np.nan).dropna()
    if valid.empty:
        return 0.25
    return float(np.clip(valid.median(), 0.0, 0.35))


def build_history_metrics(income: pd.DataFrame, balance: pd.DataFrame, cashflow: pd.DataFrame) -> pd.DataFrame:
    """Construct the historical series used to estimate the forecast.

    We build a compact table with the metrics that matter most for a DCF:
    - revenue
    - EBITDA-ish operating profit
    - effective tax rate
    - capex
    - D&A
    - net working capital proxy
    """
    revenue_key = pick_metric(income, ["Total Revenue", "Revenue", "Operating Revenue", "Net Sales"])
    ebit_key = pick_metric(income, ["Operating Income", "EBIT", "Income Before Tax", "Pretax Income"])
    tax_key = pick_metric(income, ["Income Tax Expense", "Tax Expense", "Tax Provision", "Taxes", "Income Tax Provision"])
    pretax_key = pick_metric(income, ["Income Before Tax", "Pretax Income", "Earnings Before Tax", "Operating Income Before Tax"])

    dep_key = pick_metric(cashflow, ["Depreciation", "Depreciation And Amortization", "D&A", "Amortization", "Reconciled Depreciation"])
    capex_key = pick_metric(cashflow, ["Capital Expenditures", "Capital Expenditure", "Purchase Of Property Plant And Equipment", "Capital expenditure"])

    current_assets_key = pick_metric(balance, ["Total Current Assets", "Current Assets", "Assets Current"])
    current_liab_key = pick_metric(balance, ["Total Current Liabilities", "Current Liabilities", "Liabilities Current"])
    cash_key = pick_metric(balance, ["Cash And Cash Equivalents", "Cash", "Cash And Short Term Investments"])
    debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt", "Net Debt"])

    hist = pd.DataFrame(index=income.index)
    hist["Revenue"] = income[revenue_key] if revenue_key else pd.Series(np.nan, index=income.index)
    hist["EBIT"] = income[ebit_key] if ebit_key else pd.Series(np.nan, index=income.index)
    hist["Tax Expense"] = income[tax_key] if tax_key else pd.Series(np.nan, index=income.index)
    hist["Pretax Income"] = income[pretax_key] if pretax_key else pd.Series(np.nan, index=income.index)
    hist["Depreciation"] = cashflow[dep_key] if dep_key else pd.Series(np.nan, index=income.index)
    hist["Capex"] = (-cashflow[capex_key]) if capex_key else pd.Series(np.nan, index=income.index)

    if current_assets_key and current_liab_key:
        hist["NWC"] = balance[current_assets_key] - balance[current_liab_key]
        if cash_key:
            hist["NWC"] = hist["NWC"] - balance[cash_key]
        if debt_key:
            hist["NWC"] = hist["NWC"] + balance[debt_key]
    else:
        hist["NWC"] = np.nan

    tax_series = hist["Tax Expense"].copy() if "Tax Expense" in hist.columns else hist["Tax Provision"].copy() if "Tax Provision" in hist.columns else pd.Series(np.nan, index=hist.index)
    pretax_series = hist["Pretax Income"].copy() if "Pretax Income" in hist.columns else hist["Income Before Tax"].copy() if "Income Before Tax" in hist.columns else pd.Series(np.nan, index=hist.index)

    hist["Tax Rate"] = tax_series / pretax_series.replace(0, np.nan)
    hist["EBIT Margin"] = hist["EBIT"] / hist["Revenue"]
    hist["Capex Margin"] = hist["Capex"] / hist["Revenue"]
    hist["D&A Margin"] = hist["Depreciation"] / hist["Revenue"]
    hist["NWC Margin"] = hist["NWC"] / hist["Revenue"]

    return hist.dropna(how="all")


def build_ufcf_projection(hist: pd.DataFrame, years: int = 5) -> pd.DataFrame:
    """Project unlevered free cash flow for five years.

    UNLEVERED FREE CASH FLOW (UFCF):
    UFCF is the cash available to both debt and equity holders before any financing decisions.
    It represents the true economic cash generation of the business.

    The formula:
    NOPAT = EBIT × (1 - tax rate)  [operating profit after tax, before financing]
    + Depreciation & Amortization  [non-cash charge added back]
    - Capital Expenditures         [cash spent on equipment, property, etc.]
    - Change in Net Working Capital [cash tied up in receivables, inventory, payables]
    ___________________________________________________________________________________________
    = UFCF                         [free cash available to all capital providers]

    We project this forward 5 years using historical margins to get the explicit forecast period.
    Beyond year 5, we estimate a terminal value (perpetual growth).
    """
    latest_year = hist.iloc[-1]
    revenue_growth = (latest_year["Revenue"] / hist["Revenue"].iloc[0]) ** (1 / max(len(hist) - 1, 1)) - 1
    revenue_growth = float(np.clip(revenue_growth, -0.10, 0.12))

    ebit_margin = hist["EBIT Margin"].dropna().mean()
    tax_rate = hist["Tax Rate"].dropna().median()
    d_and_a_margin = hist["D&A Margin"].dropna().mean()
    capex_margin = hist["Capex Margin"].dropna().mean()
    nwc_margin = hist["NWC Margin"].dropna().mean()

    revenue_forecast = []
    base_revenue = float(latest_year["Revenue"])
    for year in range(1, years + 1):
        revenue_forecast.append(base_revenue * (1 + revenue_growth) ** year)

    forecast = pd.DataFrame({
        "Year": np.arange(1, years + 1),
        "Revenue": revenue_forecast,
    })
    # Operating profit scaled by revenue growth; apply historical EBIT margin
    forecast["EBIT"] = forecast["Revenue"] * ebit_margin
    forecast["Tax Rate"] = tax_rate
    
    # NOPAT: Net Operating Profit After Tax. This is EBIT after accounting for cash taxes.
    # It represents profit available to all capital providers (before financing).
    forecast["NOPAT"] = forecast["EBIT"] * (1 - forecast["Tax Rate"])
    
    # D&A: Depreciation & Amortization. Non-cash charges that reduce accounting profit
    # but don't affect cash, so we add them back to get true economic cash generation.
    forecast["D&A"] = forecast["Revenue"] * d_and_a_margin
    
    # Capex: Capital expenditures needed to maintain and grow the asset base.
    # This is a true cash outflow that reduces free cash flow.
    forecast["Capex"] = forecast["Revenue"] * capex_margin
    
    # Net Working Capital: cash tied up in day-to-day operations (receivables, inventory minus payables).
    forecast["NWC"] = forecast["Revenue"] * nwc_margin

    # Delta NWC: year-over-year change in working capital. If NWC increases, the company
    # must invest cash; if it decreases, the company frees up cash.
    forecast["Delta NWC"] = forecast["NWC"].diff().fillna(0.0)
    
    # UFCF = NOPAT + D&A - Capex - Delta NWC
    # This is the cash available each year to both debt and equity holders.
    forecast["UFCF"] = (
        forecast["NOPAT"]
        + forecast["D&A"]
        - forecast["Capex"]
        - forecast["Delta NWC"]
    )

    return forecast


def estimate_cost_of_debt(balance: pd.DataFrame, income: pd.DataFrame) -> float:
    """Estimate the after-tax cost of debt from actual interest burden.

    COST OF DEBT (Rd):
    The cost of debt is the effective interest rate the company pays on its outstanding
    debt. We estimate this as:
    - Pre-tax cost of debt = annual interest expense / total debt outstanding
    - After-tax cost of debt = pre-tax cost * (1 - tax rate)
    The tax adjustment reflects the fact that interest is tax-deductible, giving the
    company a tax shield. A 5% cost of debt at a 25% tax rate is only 3.75% after-tax.

    This is a workable proxy when market debt yields are not available.
    """
    interest_key = pick_metric(income, ["Interest Expense", "Interest And Debt Expense", "Interest Expense Net"])
    debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])

    if not interest_key or not debt_key:
        return 0.052

    latest_interest = latest_value(income[interest_key])
    latest_debt = latest_value(balance[debt_key])
    if np.isnan(latest_interest) or np.isnan(latest_debt) or latest_debt <= 0:
        return 0.052

    tax_rate = robust_tax_rate(income)
    # Pre-tax cost is raw interest burden; multiply by (1 - tax_rate) to get the after-tax cost
    # that represents the true economic cost to equity holders (debt is cheaper because interest is deductible).
    pre_tax_cost_debt = latest_interest / latest_debt if latest_debt > 0 else 0.06
    return float(pre_tax_cost_debt * (1 - tax_rate))


def estimate_capm_wacc(info: Dict, balance: pd.DataFrame, income: pd.DataFrame) -> Dict[str, float]:
    """Estimate WACC using CAPM for cost of equity and book debt weights.

    WEIGHTED AVERAGE COST OF CAPITAL (WACC):
    WACC is the discount rate used to value a company's unlevered cash flows. It represents
    the blended required return that all capital providers (debt holders and equity investors)
    expect to earn on their investment in the company.

    Formula: WACC = (E/V) * Re + (D/V) * Rd * (1 - Tc)

    Where:
    - E/V = weight of equity in capital structure (market cap / total value)
    - Re = cost of equity, estimated via CAPM
    - D/V = weight of debt in capital structure (total debt / total value)
    - Rd = cost of debt (interest rate)
    - Tc = corporate tax rate

    CAPM (Capital Asset Pricing Model) for cost of equity:
    Re = Rf + β * (Rm - Rf)
    - Rf = risk-free rate (~4.2% US 10-year Treasury)
    - β = beta (stock volatility relative to market; β=1 means market-level volatility)
    - (Rm - Rf) = equity risk premium (~5% typical assumption)
    
    For Varex, beta < 1 means the stock is less volatile than the overall market.
    """
    market_cap = float(info.get("marketCap", 0.0) or 0.0)
    shares = float(info.get("sharesOutstanding", 0.0) or 0.0)
    price = float(info.get("currentPrice", 0.0) or 0.0)
    if market_cap <= 0 and price > 0 and shares > 0:
        market_cap = price * shares

    debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])
    debt = latest_value(balance[debt_key]) if debt_key else 0.0

    if debt <= 0:
        debt = 0.0

    beta = float(info.get("beta", 1.2) or 1.2)  # Actual beta from yfinance; <1 = less volatile than market
    risk_free = 0.042  # Approximate 10-year US Treasury yield as of Aug 2026.
    market_risk_premium = 0.05  # Historical equity risk premium over risk-free rate.
    # CAPM: cost of equity = risk-free + (sensitivity to market * market premium)
    cost_of_equity = risk_free + beta * market_risk_premium

    cost_of_debt = estimate_cost_of_debt(balance, income)
    tax_rate = robust_tax_rate(income)
    tax_rate = float(np.clip(tax_rate, 0.0, 0.35))

    total_capital = market_cap + debt
    if total_capital <= 0:
        weight_equity = 0.7
        weight_debt = 0.3
    else:
        # Capital structure weights: how much of the firm is financed by equity vs. debt
        weight_equity = market_cap / total_capital
        weight_debt = debt / total_capital

    # WACC is the weighted blend of cost of equity and after-tax cost of debt.
    # Higher WACC = higher risk = lower intrinsic value.
    wacc = weight_equity * cost_of_equity + weight_debt * cost_of_debt * (1 - tax_rate)

    return {
        "beta": beta,
        "risk_free": risk_free,
        "market_risk_premium": market_risk_premium,
        "cost_of_equity": cost_of_equity,
        "cost_of_debt": cost_of_debt,
        "after_tax_cost_of_debt": cost_of_debt * (1 - tax_rate),
        "wacc": wacc,
        "weight_equity": weight_equity,
        "weight_debt": weight_debt,
    }


def discount_cash_flows(ufcf: pd.DataFrame, wacc: float) -> pd.DataFrame:
    """Discount explicit forecast cash flows back to present value.

    PRESENT VALUE AND DISCOUNTING:
    A dollar today is worth more than a dollar in the future because you can invest it.
    We discount future cash flows by dividing by (1 + WACC)^t, where t is years in the future.

    Formula: PV = CF_t / (1 + WACC)^t

    For example, if WACC is 7% and we expect $100 million in year 3:
    PV = $100M / (1.07^3) = $100M / 1.225 ≈ $81.6M today

    The higher the WACC (more risky firm), the more we discount future cash flows,
    resulting in a lower present value.
    """
    df = ufcf.copy()
    # Calculate the discount factor for each year: (1 + WACC)^year
    df["PV Factor"] = (1 + wacc) ** df["Year"]
    # Divide future cash flow by the discount factor to get present value
    df["PV UFCF"] = df["UFCF"] / df["PV Factor"]
    return df


def terminal_value_gordon(ufcf: pd.DataFrame, wacc: float, terminal_growth: float) -> float:
    """Gordon growth model terminal value.

    TERMINAL VALUE (Gordon Growth Model):
    We can only forecast explicitly for 5 years. Beyond that, we assume the firm grows
    at a constant "terminal growth rate" indefinitely. The terminal value captures
    the value of all cash flows from year 6 onward.

    Formula: TV = FCF_year6 / (WACC - g)
    where FCF_year6 = FCF_year5 * (1 + g) and g = terminal growth rate

    Key assumptions:
    - g must be < WACC (otherwise the formula breaks down and value explodes)
    - g should be conservative: typically 2-3%, around long-run nominal GDP growth
    - The terminal value usually represents 60-80% of total enterprise value
    
    For Varex, we use 2.5% as a realistic long-term growth rate given the stable
    industrial/medical imaging market.
    """
    # Safety check: if growth >= WACC, the model is unstable and the value is infinite.
    # This represents an unrealistic scenario and should be flagged.
    if wacc <= terminal_growth:
        return np.nan
    
    # Extrapolate year 5 cash flow to year 6, growing at the terminal rate
    year_6_fcf = float(ufcf["UFCF"].iloc[-1] * (1 + terminal_growth))
    
    # Gordon growth perpetuity: cash flow in year 6 divided by (WACC - growth)
    # This assumes constant growth forever and is capitalized at the WACC spread
    tv = year_6_fcf / (wacc - terminal_growth)
    return tv


def build_exit_multiple_comps(comp_symbols: List[str]) -> pd.DataFrame:
    """Cross-check the Gordon growth TV with an EV/EBITDA exit multiple.

    EXIT MULTIPLE APPROACH (Cross-check):
    An alternative way to estimate terminal value is to assume the company is sold at
    a market multiple (e.g., EV/EBITDA) typical for the industry. This is a reality check:
    if our Gordon growth terminal value implies an unrealistic exit multiple, we know
    our assumptions are off.

    Trading Comparables (Comps):
    - GEHC (GE HealthCare): large medical imaging/healthcare IT conglomerate
    - TDY (Teledyne): diversified electronics & imaging; acquirer of Varex
    - Varex itself: no pure-play public comp, so GEHC/TDY serve as directional proxies

    The idea: take the median EV/EBITDA from peers and apply it to Varex's terminal
    year EBITDA. This gives us an alternative estimate of terminal value that should
    be in the same ballpark as the Gordon growth TV.
    """
    rows = []
    for symbol in comp_symbols:
        data = fetch_statement_data(symbol)
        info = data["info"]
        income = data["income"]
        balance = data["balance"]
        cashflow = data["cashflow"]

        market_cap = float(info.get("marketCap", 0.0) or 0.0)
        if market_cap <= 0:
            shares = float(info.get("sharesOutstanding", 0.0) or 0.0)
            price = float(info.get("currentPrice", 0.0) or 0.0)
            market_cap = shares * price

        debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])
        cash_key = pick_metric(balance, ["Cash And Cash Equivalents", "Cash", "Cash And Short Term Investments"])
        debt = latest_value(balance[debt_key]) if debt_key else 0.0
        cash = latest_value(balance[cash_key]) if cash_key else 0.0

        ebitda_key = pick_metric(income, ["EBITDA", "Operating Income", "Earnings Before Interest Taxes Depreciation And Amortization"])
        if not ebitda_key:
            dep_key = pick_metric(cashflow, ["Depreciation", "Depreciation And Amortization", "D&A", "Amortization"])
            op_key = pick_metric(income, ["Operating Income", "EBIT", "Income Before Tax"])
            ebitda = latest_value(income[op_key]) + latest_value(cashflow[dep_key])
        else:
            ebitda = latest_value(income[ebitda_key])

        if np.isnan(ebitda) or ebitda <= 0:
            ebitda = 1.0

        ev = market_cap + debt - cash
        ev_ebitda = ev / ebitda
        rows.append({
            "Ticker": symbol,
            "MarketCap": market_cap,
            "Debt": debt,
            "Cash": cash,
            "EV": ev,
            "EBITDA": ebitda,
            "EV_EBITDA": ev_ebitda,
        })

    return pd.DataFrame(rows)


def estimate_value_per_share_via_dcf(symbol: str, offer_price: float = OFFER_PRICE) -> Dict[str, float]:
    """Run the full DCF and return valuation metrics.

    FULL DCF WORKFLOW:
    1. Pull financial statements (income, balance sheet, cash flow) from yfinance
    2. Build historical metrics (margins, growth rates, working capital ratios)
    3. Project 5-year unlevered free cash flows
    4. Estimate WACC using CAPM (cost of equity and cost of debt)
    5. Discount forecast period cash flows to present value
    6. Calculate terminal value using Gordon growth model
    7. Sum PV of forecast + PV of terminal to get enterprise value
    8. Subtract net debt to get equity value
    9. Divide by shares outstanding to get implied share price
    10. Cross-check with exit multiple approach (EV/EBITDA comps)
    11. Compare to offer price

    This yields a price estimate per share, which can then be compared directly
    with the acquisition offer in the deal note.
    """
    # Step 1-3: Fetch data, build history, and project forward
    data = fetch_statement_data(symbol)
    income = data["income"]
    balance = data["balance"]
    cashflow = data["cashflow"]
    info = data["info"]
    hist = build_history_metrics(income, balance, cashflow)
    forecast = build_ufcf_projection(hist, years=5)

    # Step 4: Estimate WACC via CAPM
    wacc_info = estimate_capm_wacc(info, balance, income)
    wacc = float(wacc_info["wacc"])
    # Terminal growth assumption: conservative perpetual growth rate
    # Should be < WACC and realistic for long-term GDP + company-specific growth
    terminal_growth = 0.025

    # Step 5-7: Discount cash flows and calculate enterprise value
    pv = discount_cash_flows(forecast, wacc)
    # Terminal value is discounted back 5 years to get its present value
    pv_terminal = terminal_value_gordon(forecast, wacc, terminal_growth) / ((1 + wacc) ** 5)
    # Total enterprise value = sum of discounted forecast period cash flows + PV of terminal value
    enterprise_value = float(pv["PV UFCF"].sum() + pv_terminal)

    # Step 8: Extract net debt from balance sheet
    debt_key = pick_metric(balance, ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])
    cash_key = pick_metric(balance, ["Cash And Cash Equivalents", "Cash", "Cash And Short Term Investments"])
    debt = latest_value(balance[debt_key]) if debt_key else 0.0
    cash = latest_value(balance[cash_key]) if cash_key else 0.0
    # Net debt = total debt minus cash. Equity value = enterprise value - net debt
    net_debt = debt - cash

    # Step 9: Get shares outstanding for per-share calculation
    shares = float(info.get("sharesOutstanding", 0.0) or 0.0)
    last_price = float(info.get("currentPrice", 0.0) or 0.0)
    if shares <= 0 and last_price > 0:
        shares = float(info.get("marketCap", 0.0) or 0.0) / last_price

    # Implied share price from Gordon growth DCF: equity value / shares
    equity_value = enterprise_value - net_debt
    implied_price = equity_value / shares if shares > 0 else np.nan

    # Step 10: Cross-check with exit multiple approach
    comps = build_exit_multiple_comps(COMPS)
    # Use median EV/EBITDA from comparable companies
    exit_multiple = float(comps["EV_EBITDA"].median())
    # Terminal year EBITDA = EBIT + D&A (operating earnings before financing and tax effects)
    terminal_ebitda = float(forecast["EBIT"].iloc[-1] + forecast["D&A"].iloc[-1])
    # Terminal value via exit multiple = apply median comp multiple to terminal EBITDA
    tv_exit = terminal_ebitda * exit_multiple
    # Discount terminal value back 5 years to present
    pv_exit = tv_exit / ((1 + wacc) ** 5)
    # Enterprise value using exit multiple for terminal value
    enterprise_value_exit = float(pv["PV UFCF"].sum() + pv_exit)
    # Implied share price via exit multiple approach
    implied_price_exit = (enterprise_value_exit - net_debt) / shares if shares > 0 else np.nan

    # Step 11: Compile results for reporting
    summary = {
        "wacc": wacc,
        "terminal_growth": terminal_growth,
        "beta": wacc_info["beta"],
        "cost_of_equity": wacc_info["cost_of_equity"],
        "after_tax_cost_of_debt": wacc_info["after_tax_cost_of_debt"],
        "weight_equity": wacc_info["weight_equity"],
        "weight_debt": wacc_info["weight_debt"],
        "enterprise_value_dcf": enterprise_value,
        "enterprise_value_exit_multiple": enterprise_value_exit,
        "implied_share_price_dcf": implied_price,
        "implied_share_price_exit_multiple": implied_price_exit,
        "offer_price": offer_price,
        "upside_vs_offer": implied_price / offer_price - 1,
        "gordon_terminal_value": terminal_value_gordon(forecast, wacc, terminal_growth),
        "exit_multiple": exit_multiple,
        "forecast_table": forecast,
        "discounted_table": pv,
        "comps_table": comps,
    }
    return summary


def make_sensitivity_heatmap(summary: Dict[str, float]) -> None:
    """Create a 2D sensitivity table for WACC vs terminal growth.

    SENSITIVITY ANALYSIS:
    DCF valuation depends critically on two uncertain inputs: WACC and terminal growth.
    We vary both over a reasonable range and show how the implied share price changes.

    This table shows:
    - Rows: WACC (4% to 12%), representing different risk/discount-rate scenarios
    - Columns: Terminal growth (1% to 5%), representing different perpetual growth rates
    - Cells: Implied share price for that WACC/growth combination

    The offer price ($18.90) is marked so you can see how many scenarios justify
    or reject the deal. A wide range implies high sensitivity; a narrow range means
    the valuation is relatively robust to assumption changes.
    
    This is critical for interview discussion: you want to show how confident you are
    in your base case and what would need to change for the deal to look different.
    """
    data = fetch_statement_data(TICKER)
    hist = build_history_metrics(data["income"], data["balance"], data["cashflow"])
    forecast = build_ufcf_projection(hist, years=5)

    wacc_grid = np.linspace(0.04, 0.12, 9)
    growth_grid = np.linspace(0.01, 0.05, 9)
    values = np.zeros((len(wacc_grid), len(growth_grid)))

    debt_key = pick_metric(data["balance"], ["Total Debt", "Short Long Term Debt", "Long Term Debt", "Current Debt"])
    cash_key = pick_metric(data["balance"], ["Cash And Cash Equivalents", "Cash", "Cash And Short Term Investments"])
    debt = latest_value(data["balance"][debt_key]) if debt_key else 0.0
    cash = latest_value(data["balance"][cash_key]) if cash_key else 0.0
    net_debt = debt - cash
    shares = float(data["info"].get("sharesOutstanding", 0.0) or 0.0)
    if shares <= 0:
        shares = (float(data["info"].get("marketCap", 0.0) or 0.0) / max(float(data["info"].get("currentPrice", 0.0) or 0.0), 1.0))

    for i, wacc in enumerate(wacc_grid):
        pv = discount_cash_flows(forecast, wacc)
        for j, g in enumerate(growth_grid):
            # Calculate Gordon growth terminal value for this (WACC, growth) pair
            tv = terminal_value_gordon(forecast, wacc, g)
            if np.isnan(tv):
                # If terminal growth >= WACC, the scenario is unrealistic; mark as NaN
                values[i, j] = np.nan
                continue
            # Enterprise value = PV of explicit forecast + PV of terminal value
            # Terminal value is discounted back 5 years to present
            ev = pv["PV UFCF"].sum() + tv / ((1 + wacc) ** 5)
            # Equity value = enterprise value - net debt
            # Share price = equity value / shares outstanding
            values[i, j] = (ev - net_debt) / shares

    plt.figure(figsize=(9, 7))
    ax = plt.gca()
    heatmap = ax.imshow(values, cmap="RdYlGn_r", aspect="auto", origin="lower")
    ax.set_xticks(range(len(growth_grid)))
    ax.set_yticks(range(len(wacc_grid)))
    ax.set_xticklabels([f"{g:.2%}" for g in growth_grid])
    ax.set_yticklabels([f"{w:.2%}" for w in wacc_grid])
    ax.set_xlabel("Terminal growth rate")
    ax.set_ylabel("WACC")
    ax.set_title("VREX implied share value sensitivity: WACC x terminal growth")

    for i in range(len(wacc_grid)):
        for j in range(len(growth_grid)):
            ax.text(j, i, f"${values[i, j]:.1f}", ha="center", va="center", color="black", fontsize=8)

    for idx, value in enumerate(values.flatten()):
        if abs(value - OFFER_PRICE) < 0.5:
            i = idx // len(growth_grid)
            j = idx % len(growth_grid)
            ax.scatter(j, i, s=80, facecolors="none", edgecolors="black", linewidths=1.5)

    plt.colorbar(heatmap, ax=ax, label="Implied share value ($)")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "wacc_growth_sensitivity.png", dpi=200)
    plt.close()


def make_implied_value_chart(summary: Dict[str, float]) -> None:
    """Create a simple value-vs-offer chart for presentation.

    This is not meant to be the only metric, but it is a clear way to frame the
    investment decision in a discussion or interview.
    """
    labels = ["DCF intrinsic value", "Exit multiple value", "Offer price"]
    values = [
        summary["implied_share_price_dcf"],
        summary["implied_share_price_exit_multiple"],
        OFFER_PRICE,
    ]

    plt.figure(figsize=(7, 5))
    bars = plt.bar(labels, values, color=["#2a7ae2", "#6ab36d", "#d65f5f"])
    plt.axhline(OFFER_PRICE, color="black", linestyle="--", linewidth=1.0, label="Offer price")
    plt.ylabel("Share value ($)")
    plt.title("VREX implied value vs. Teledyne offer")
    plt.grid(axis="y", linestyle="--", alpha=0.3)
    for bar, value in zip(bars, values):
        plt.text(bar.get_x() + bar.get_width() / 2, value + 0.4, f"${value:.2f}", ha="center", va="bottom")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "implied_value_vs_offer.png", dpi=200)
    plt.close()


def main() -> None:
    """Run the full valuation workflow and save clean outputs.
    
    This is the entry point: fetch data, build the DCF model, run sensitivity analysis,
    and save charts and summaries for presentation.
    """
    # Run the full DCF valuation
    summary = estimate_value_per_share_via_dcf(TICKER, OFFER_PRICE)

    # Compile key metrics into a CSV for easy inspection and presentation
    # This table shows all the critical WACC components and valuation outputs.
    summary_table = pd.DataFrame([
        {
            "Metric": "WACC",
            "Value": summary["wacc"],
        },
        {
            "Metric": "Beta",
            "Value": summary["beta"],
        },
        {
            "Metric": "Cost of equity",
            "Value": summary["cost_of_equity"],
        },
        {
            "Metric": "After-tax cost of debt",
            "Value": summary["after_tax_cost_of_debt"],
        },
        {
            "Metric": "Enterprise value (DCF)",
            "Value": summary["enterprise_value_dcf"],
        },
        {
            "Metric": "Gordon terminal value",
            "Value": summary["gordon_terminal_value"],
        },
        {
            "Metric": "Implied share price (DCF)",
            "Value": summary["implied_share_price_dcf"],
        },
        {
            "Metric": "Implied share price (exit multiple)",
            "Value": summary["implied_share_price_exit_multiple"],
        },
        {
            "Metric": "Offer price",
            "Value": summary["offer_price"],
        },
        {
            "Metric": "Upside vs offer",
            "Value": summary["upside_vs_offer"],
        },
    ])
    summary_table.to_csv(OUTPUT_DIR / "vrex_dcf_summary.csv", index=False)

    # Generate sensitivity heatmap: shows how implied value changes with WACC and terminal growth
    make_sensitivity_heatmap(summary)
    # Generate value comparison chart: DCF value, exit multiple value, and offer price side-by-side
    make_implied_value_chart(summary)

    print("WACC:", round(summary["wacc"], 4))
    print("Beta:", round(summary["beta"], 3))
    print("Implied share price (DCF): $", round(summary["implied_share_price_dcf"], 2))
    print("Implied share price (exit multiple): $", round(summary["implied_share_price_exit_multiple"], 2))
    print("Offer price: $", round(summary["offer_price"], 2))
    print("Upside vs offer:", round(summary["upside_vs_offer"] * 100, 2), "%")
    print("Comparable EV/EBITDA median:", round(summary["exit_multiple"], 2), "x")

    print("\n" + "="*70)
    print("INTERPRETATION NOTES:")
    print("="*70)
    print("- Varex does not have a clean pure-play public comp; GEHC and TDY are used")
    print("  only as directional cross-checks for valuation multiples.")
    print("- Terminal value represents perpetual growth beyond year 5 and is the largest")
    print("  driver of valuation; small changes in terminal growth rate have large effects.")
    print("- The sensitivity heatmap shows which WACC/growth combinations justify or")
    print("  reject the $18.90 offer. Interpret this in context of your confidence in")
    print("  the cost of capital and long-term growth assumptions.")
    print("- Charts and CSV saved in output/ for presentation.")
    print("="*70)


if __name__ == "__main__":
    # Execute the valuation workflow
    main()
